import request from 'supertest';
import { INestApplication } from '@nestjs/common';
import { createTestApp, closeTestApp } from './support/app';
import { getAccessToken } from './support/keycloak';
import { registerShop } from './support/register';
import { buildMinimalPdf } from './support/fixtures';

/**
 * SRS §18 Security / §22 "API tests for authentication, shop isolation".
 * Uses real OIDC access tokens from the dev Keycloak instance (password
 * grant against the seeded demo admin/shopkeeper accounts) so this
 * exercises the actual KeycloakAuthGuard -> RolesGuard -> UsersService
 * resolution chain end to end, not a stubbed request.user.
 */
// Fixed demo shop id from prisma/seed.ts — stable across runs, unlike its
// QR *code*, which an admin can regenerate at any time from the dashboard.
const DEMO_SHOP_ID = '33333333-3333-3333-3333-333333333333';

describe('Authentication & role-based authorization (e2e)', () => {
  let app: INestApplication;
  let server: any;
  let adminToken: string;
  let shopkeeperToken: string;
  let demoShopCode: string;

  beforeAll(async () => {
    app = await createTestApp();
    server = app.getHttpServer();
    [adminToken, shopkeeperToken] = await Promise.all([
      getAccessToken('admin', 'admin'),
      getAccessToken('shopkeeper.demo@printsetu.local', 'Shop@12345'),
    ]);

    // Fetch (never hardcode) the demo shop's *current* active QR code — it
    // may have been regenerated by a human operator exploring the app.
    const qrRes = await request(server)
      .get(`/api/admin/qr/${DEMO_SHOP_ID}`)
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(200);
    demoShopCode = qrRes.body.code;
  });

  afterAll(async () => {
    await closeTestApp(app);
  });

  it('rejects an unauthenticated request to a protected endpoint', async () => {
    await request(server).get('/api/admin/shops').expect(401);
  });

  it('rejects a garbage/forged bearer token', async () => {
    await request(server)
      .get('/api/admin/shops')
      .set('Authorization', 'Bearer this-is-not-a-real-jwt')
      .expect(401);
  });

  it('allows a real admin token onto an admin-only endpoint', async () => {
    const res = await request(server)
      .get('/api/admin/shops')
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(200);
    expect(Array.isArray(res.body.items)).toBe(true);
    expect(res.body.items.some((s: any) => s.shopCode === 'SHOP-DEMO001')).toBe(true);
  });

  it('rejects a shopkeeper token on an admin-only endpoint (role isolation)', async () => {
    await request(server)
      .get('/api/admin/shops')
      .set('Authorization', `Bearer ${shopkeeperToken}`)
      .expect(403);
  });

  it('rejects an admin token on a shopkeeper-only endpoint', async () => {
    await request(server)
      .get('/api/shop/print-jobs')
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(403);
  });

  it("resolves the shopkeeper token to their own shop's profile only", async () => {
    const res = await request(server)
      .get('/api/shop/profile')
      .set('Authorization', `Bearer ${shopkeeperToken}`)
      .expect(200);
    expect(res.body.shop.shopCode).toBe('SHOP-DEMO001');
  });

  it('lets the shopkeeper see their own (empty-or-not) print queue without needing a shop param', async () => {
    const res = await request(server)
      .get('/api/shop/print-jobs')
      .set('Authorization', `Bearer ${shopkeeperToken}`)
      .expect(200);
    expect(Array.isArray(res.body)).toBe(true);
  });

  it("a second shop's shopkeeper cannot preview the demo shop's document (real cross-tenant isolation, SRS §5.1)", async () => {
    // 1. A brand new shop registers itself (shop + shopkeeper login in one
    // step) — exercises the real registration -> Keycloak provisioning path.
    const { accessToken: otherShopkeeperToken } = await registerShop(server, 'isolation', {
      mobile: '9111111111',
    });

    // 2. A document is uploaded for the ORIGINAL demo shop via the real
    // public customer flow.
    const uploadRes = await request(server)
      .post('/api/documents')
      .field('shopCode', demoShopCode)
      .attach('file', buildMinimalPdf(), {
        filename: 'isolation.pdf',
        contentType: 'application/pdf',
      })
      .expect(201);
    const documentId = uploadRes.body.documentId;

    // 3. The new shop's shopkeeper — a real, distinct authenticated
    // identity — must be denied; the original demo shopkeeper (who
    // actually owns SHOP-DEMO001) must be allowed.
    await request(server)
      .get(`/api/shop/documents/${documentId}/preview-url`)
      .set('Authorization', `Bearer ${otherShopkeeperToken}`)
      .expect(403);

    await request(server)
      .get(`/api/shop/documents/${documentId}/preview-url`)
      .set('Authorization', `Bearer ${shopkeeperToken}`)
      .expect(200);
  }, 20_000);
});
